#!/bin/bash

function webifyfile {
    filepath=$1
    # file may or may not have .extension
    filename=$(basename ${filepath})
    short_filename=${filename%.*}

    # where is the webpage input dir?
    input_dir=/home/eeaol/web/input/notes

    # get the date from the file, assuming dd/mm/yyyy format and
    # converting to yyyy-mm-dd
    date=$(grep -i -m 1 'date: [0-9]./[0-9]./[0-9]...' $filepath |\
            sed -e 's/^[^0-9]*//' \
                -e 's/\(..\)\/\(..\)\/\(....\)/\3-\2-\1/')

    title=$(grep -i -m 1 'title: .*' $filepath)

    # make a temporary container for the content
    cat $filepath >> tmpfc

    # remove the old title from the file
    # sed -i '/title:.*/d' $newfilepath
    # remove the old date from the file
    # sed -i '/[Dd]ate: [0-9].\/[0-9].\/[0-9].../d' $newfilepath
    # remove all the metadata from the file (it has to be separated
    # from the content by a blank line)
    sed -i '1,/^$/d' tmpfc

    # add the metadata to the start of the file
    post=$(echo $short_filename | sed 's/[_-]/ /g')
    echo "$title" >> tmpf
    echo "post: $post" >> tmpf
    echo "date: $date" >> tmpf
    echo -e "---\n" >> tmpf
    cat tmpfc >> tmpf
    # tmpf is now full of header and content

    # create directories for the file to live in 
    year=${date:0:4}
    month=${date:5:2}
    day=${date:8:2}

    newdaydir=${input_dir}/$year/$month/$day
    newmonthdir=${input_dir}/$year/$month
    mkdir -p $newdaydir
    mkdir -p $newmonthdir
    newdayfilepath=$newdaydir/${short_filename}.md
    newmonthfilepath=$newmonthdir/${short_filename}.md
    cp tmpf $newdayfilepath
    cp tmpf $newmonthfilepath

    # clean up
    rm -f tmpf tmpfc
}

for f in $*; do
    webifyfile $f;
done
